# Generated by Django 4.2.7 on 2023-11-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wikipage2301',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('keyword', models.CharField(default='', max_length=32)),
                ('views', models.CharField(max_length=256)),
            ],
            options={
                'indexes': [models.Index(fields=['keyword'], name='idx_K')],
            },
        ),
    ]
