# Generated by Django 4.2.7 on 2023-11-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage2301',
            name='id',
            field=models.CharField(default='', max_length=128, primary_key=True, serialize=False),
        ),
    ]
