# Generated by Django 4.2.7 on 2023-11-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wikipage102023',
            fields=[
                ('id', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('keyword', models.CharField(default='', max_length=32)),
                ('views', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'wiki_page_10_2023',
            },
        ),
        migrations.CreateModel(
            name='Wikipage112023',
            fields=[
                ('id', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('keyword', models.CharField(default='', max_length=32)),
                ('views', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'wiki_page_11_2023',
            },
        ),
        migrations.CreateModel(
            name='Wikipage122023',
            fields=[
                ('id', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('keyword', models.CharField(default='', max_length=32)),
                ('views', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'wiki_page_12_2023',
            },
        ),
        migrations.CreateModel(
            name='Wikipage22023',
            fields=[
                ('id', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('keyword', models.CharField(default='', max_length=32)),
                ('views', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'wiki_page_2_2023',
            },
        ),
        migrations.CreateModel(
            name='Wikipage32023',
            fields=[
                ('id', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('keyword', models.CharField(default='', max_length=32)),
                ('views', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'wiki_page_3_2023',
            },
        ),
        migrations.CreateModel(
            name='Wikipage42023',
            fields=[
                ('id', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('keyword', models.CharField(default='', max_length=32)),
                ('views', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'wiki_page_4_2023',
            },
        ),
        migrations.CreateModel(
            name='Wikipage52023',
            fields=[
                ('id', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('keyword', models.CharField(default='', max_length=32)),
                ('views', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'wiki_page_5_2023',
            },
        ),
        migrations.CreateModel(
            name='Wikipage62023',
            fields=[
                ('id', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('keyword', models.CharField(default='', max_length=32)),
                ('views', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'wiki_page_6_2023',
            },
        ),
        migrations.CreateModel(
            name='Wikipage72023',
            fields=[
                ('id', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('keyword', models.CharField(default='', max_length=32)),
                ('views', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'wiki_page_7_2023',
            },
        ),
        migrations.CreateModel(
            name='Wikipage82023',
            fields=[
                ('id', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('keyword', models.CharField(default='', max_length=32)),
                ('views', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'wiki_page_8_2023',
            },
        ),
        migrations.CreateModel(
            name='Wikipage92023',
            fields=[
                ('id', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('keyword', models.CharField(default='', max_length=32)),
                ('views', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'wiki_page_9_2023',
            },
        ),
        migrations.RenameModel(
            old_name='Wikipage2301',
            new_name='Wikipage12023',
        ),
        migrations.RenameIndex(
            model_name='wikipage12023',
            new_name='idx_keyword_1_2023',
            old_name='idx_K',
        ),
        migrations.AlterModelTable(
            name='wikipage12023',
            table='wiki_page_1_2023',
        ),
        migrations.AddIndex(
            model_name='wikipage92023',
            index=models.Index(fields=['keyword'], name='idx_keyword_9_2023'),
        ),
        migrations.AddIndex(
            model_name='wikipage82023',
            index=models.Index(fields=['keyword'], name='idx_keyword_8_2023'),
        ),
        migrations.AddIndex(
            model_name='wikipage72023',
            index=models.Index(fields=['keyword'], name='idx_keyword_7_2023'),
        ),
        migrations.AddIndex(
            model_name='wikipage62023',
            index=models.Index(fields=['keyword'], name='idx_keyword_6_2023'),
        ),
        migrations.AddIndex(
            model_name='wikipage52023',
            index=models.Index(fields=['keyword'], name='idx_keyword_5_2023'),
        ),
        migrations.AddIndex(
            model_name='wikipage42023',
            index=models.Index(fields=['keyword'], name='idx_keyword_4_2023'),
        ),
        migrations.AddIndex(
            model_name='wikipage32023',
            index=models.Index(fields=['keyword'], name='idx_keyword_3_2023'),
        ),
        migrations.AddIndex(
            model_name='wikipage22023',
            index=models.Index(fields=['keyword'], name='idx_keyword_2_2023'),
        ),
        migrations.AddIndex(
            model_name='wikipage122023',
            index=models.Index(fields=['keyword'], name='idx_keyword_12_2023'),
        ),
        migrations.AddIndex(
            model_name='wikipage112023',
            index=models.Index(fields=['keyword'], name='idx_keyword_11_2023'),
        ),
        migrations.AddIndex(
            model_name='wikipage102023',
            index=models.Index(fields=['keyword'], name='idx_keyword_10_2023'),
        ),
    ]
