# Generated by Django 4.2.6 on 2023-10-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipage', '0002_rename_count_wikipage_views_wikipage_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
