# Generated by Django 4.2.7 on 2023-11-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipage', '0002_wikipage102023_wikipage112023_wikipage122023_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wikitop10',
            fields=[
                ('date', models.CharField(default='2023-01-01', max_length=16, primary_key=True, serialize=False)),
                ('title_1', models.CharField(default='', max_length=128)),
                ('views_1', models.CharField(default='', max_length=32)),
                ('title_2', models.CharField(default='', max_length=128)),
                ('views_2', models.CharField(default='', max_length=32)),
                ('title_3', models.CharField(default='', max_length=128)),
                ('views_3', models.CharField(default='', max_length=32)),
                ('title_4', models.CharField(default='', max_length=128)),
                ('views_4', models.CharField(default='', max_length=32)),
                ('title_5', models.CharField(default='', max_length=128)),
                ('views_5', models.CharField(default='', max_length=32)),
                ('title_6', models.CharField(default='', max_length=128)),
                ('views_6', models.CharField(default='', max_length=32)),
                ('title_7', models.CharField(default='', max_length=128)),
                ('views_7', models.CharField(default='', max_length=32)),
                ('title_8', models.CharField(default='', max_length=128)),
                ('views_8', models.CharField(default='', max_length=32)),
                ('title_9', models.CharField(default='', max_length=128)),
                ('views_9', models.CharField(default='', max_length=32)),
                ('title_10', models.CharField(default='', max_length=128)),
                ('views_10', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
