# Generated by Django 4.2.7 on 2023-11-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipage', '0002_alter_wikipage2301_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage2301',
            name='views',
            field=models.CharField(max_length=1024),
        ),
    ]
