# Generated by Django 4.2.6 on 2023-10-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipage', '0003_wikipage_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikipage',
            name='index',
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['date', 'title'], name='idx_date_title'),
        ),
    ]
