# Generated by Django 4.2.6 on 2023-10-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipage', '0004_remove_wikipage_index_wikipage_idx_date_title'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wikipage',
            name='idx_date_title',
        ),
        migrations.RemoveField(
            model_name='wikipage',
            name='date',
        ),
        migrations.AddField(
            model_name='wikipage',
            name='keyword',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='month',
            field=models.CharField(default='0000-00', max_length=32),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='views',
            field=models.CharField(max_length=256),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['month', 'keyword', 'title'], name='idx_MKT'),
        ),
    ]
