# Generated by Django 4.2.7 on 2023-11-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipage', '0006_remove_wikipage_idx_mkt_rename_title_wikipage_pageid_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wikipage',
            name='idx_MKT',
        ),
        migrations.RenameField(
            model_name='wikipage',
            old_name='pageid',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='wikipage',
            name='keyword',
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['month', 'title'], name='idx_MT'),
        ),
    ]
